name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # This will cache node_modules based on package-lock.json

      - name: Install dependencies
        run: npm ci  # Using 'npm ci' instead of 'npm install' for more reliable builds

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build

      - name: Run Tests
        env:
          CI: true
        run: npm test